export const inputs = [
  {
    id: "1",
    name: "firstName",
    label: "First Name",
    placeholder: "First name",
    type: "text",
    pattern: "^[A-Za-z ]{2,15}$",
    error: "Name should not be empty, and within 2 to 15 characters long",
    required: true,
  },
  {
    id: "2",
    name: "lastName",
    label: "Last Name",
    placeholder: "Last name",
    type: "text",
    pattern: "^[A-Za-z]{2,15}$",
    error: "Name should not be empty, and within 2 to 15 characters long",
    required: true,
  },
  {
    id: "3",
    name: "email",
    label: "Email",
    placeholder: "Email",
    type: "email",
    error: "Should be a valid email",
    required: true,
  },
  {
    id: "4",
    name: "phonenumber",
    label: "Phone Number",
    placeholder: "phone number",
    type: "tel",
    pattern: "^\\+?\\d{3,18}$",
    error: "Phone number should contain atleast 3 to 18 digits",
    required: true,
  },
  {
    id: "5",
    name: "dob",
    label: "Date of Birth",
    placeholder: "02/01/2005",
    type: "date",
  },
  {
    id: "6",
    name: "password",
    label: "Password",
    placeholder: "Password",
    type: "password",
    pattern:
      "^(?=.*[0-9])(?=.*[A-Z])(?=.*[a-z])(?=.*[!@#$%^&*.])[a-zA-Z0-9!@#$%^&*.]{8,15}$",
    error:
      "Password should contain atleast 1 uppercase, 1 lowercase, 1 mumber, 1 special character and should be 8-15 characters long",
    required: true,
  },
  {
    id: "7",
    name: "confirmPassword",
    label: "Confirm Password",
    placeholder: "Confirm Password",
    type: "password",
    error: "Passwords do not match",
    required: true,
  },
];

export const TestId = {
  FORM_INPUT_CONTAINER: "formInputContainer",
  FORM_LABEL: "formLabel",
  FORM_INPUT: "formInput",
};
